# .streamlit/secrets.toml
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ssp0oe1gM6xLkXvLZ0XnYbvxj74fVGf3A30IMMqliP8/edit"
# Si la hoja es pública (con el link), no necesitas más. 
# Si es privada, necesitarás el service_account dict aquí.